USE DTAPROYECT;
CREATE TABLE PRODUCTS 
(
id int primary key NOT NULL,
nombre VARCHAR (255) NOT NULL,
price DECIMAL (10,2) NOT NULL,
stock int NOT NULL,
deliver VARCHAR (255) NOT NULL,
createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
lastUpdate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
);